from distutils.core import setup, Extension
setup(name='ftgl',
      version='0.1',
      ext_modules=[Extension('_ftgl', 
			     ['ftgl_wrap.cxx',
	'FTGL/src/FTBitmapGlyph.cpp',
	'FTGL/src/FTCharmap.cpp',
	'FTGL/src/FTContour.cpp',
	'FTGL/src/FTExtrdGlyph.cpp',
	'FTGL/src/FTFace.cpp',
	'FTGL/src/FTFont.cpp',
	'FTGL/src/FTGLBitmapFont.cpp',
	'FTGL/src/FTGLExtrdFont.cpp',
	'FTGL/src/FTGLOutlineFont.cpp',
	'FTGL/src/FTGLPixmapFont.cpp',
	'FTGL/src/FTGLPolygonFont.cpp',
	'FTGL/src/FTGLTextureFont.cpp',
	'FTGL/src/FTGlyph.cpp',
	'FTGL/src/FTGlyphContainer.cpp',
	'FTGL/src/FTLibrary.cpp',
	'FTGL/src/FTOutlineGlyph.cpp',
	'FTGL/src/FTPixmapGlyph.cpp',
	'FTGL/src/FTPoint.cpp',
	'FTGL/src/FTPolyGlyph.cpp',
	'FTGL/src/FTSize.cpp',
	'FTGL/src/FTTextureGlyph.cpp',
	'FTGL/src/FTVectoriser.cpp',
	],
     include_dirs=['f:\\program files\\freetype\\include', 
	   'f:\\program files\\freetype\\include\\freetype2',
	   'FTGL\\include'],
     libraries=['opengl32', 'glu32', 'freetype'],
     library_dirs=['f:\\program files\\freetype\\lib']),
      ])
